---
- name: building CentOS6 HAproxy 
  become: yes
  hosts: prdx-haproxy116
  vars:
    content: /home/ansible/Lab_Porject/webserver-playbooks
  tasks:

  - name: installing haproxy
    yum:
      name: haproxy
      state: latest

  - name: start and enable haproxy
    service:
      name: haproxy
      state: started
      enabled: yes

  - name: configuring haproxy
    template:
      src: "{{ content }}/ansible-templates/haproxy_6.cfg.j2"
      dest: /etc/haproxy/haproxy.cfg

  - name: restart haproxy
    service:
      name: haproxy
      state: restarted
