---
- name: deploying apache config changes across multiple webservers
  hosts: web
  become_true: yes
  tasks:
 

  - name: installing apache 
    yum: 
      name: httpd
      service: latest

  - name: start, and enable http service
    service:
      name: httpd
      state: started
  
  - name: creating a html directory to display content
    file:
      path: /var/www/html/team1/
      state: directory
