---
- name: installing apache accross multiple servers
  remote_user: ansible
  gather_facts: yes
  hosts: web
  tasks:

# - name: installing apache
#    yum:
#     name: httpd
#     service: latest

  - name: start, and enable http service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: creating a html directory to server content
    file:
      path: /var/www/html/team1/
      state: directory
      mode: '0777'
  - name: creating an index file within team1 html directory
    file:
      path: /var/www/html/team1/index.html
      state: file
