---
- name: installing apache accross multiple servers
  become_user: ansible
  hosts: web
  tasks:

  - name: installing apache
    yum:
      name: httpd
      service: latest

  - name: start, and enable http service
    service:
      name: httpd
      state: started

  - name: creating a html directory to server content
