---
- name: installing apache accross multiple servers
  remote_user: ansible
  gather_facts: yes
  hosts: prdx-webserver217.ziyotek1.local
  vars:
    github_folder: "home/ansible/Lab_Porject/webserver-playbooks/"

  tasks:
  - name: installing apache
    yum:
      name: httpd
      service: latest
  - name: start, and enable http service
    service:
      name: httpd
      state: started
      enabled: yes
  - name: creating a html directory to server content
    file:
      path: /var/www/html/team1/
      state: directory
      mode: '0777'
  - name: creating an index file within team1 html directory
    file:
      path: /var/www/html/team1/index.html
      state: touch
      mode: '0777'
  - name: Opening firewalls ---- Port 80 (HTTP enabled)
    firewalld:
      service: http
      permanent: yes
      state: enabled
    notify: restart firewalld
  handlers:
  - name: restart firewalld
    systemd:
      name: firewalld
      state: restarted
# - name: Restarting Firewall Daemon
#   service:
#     name: firewalld
#     state: restarted
  - name: uploading content to our index file, and restart apache if a config has been made.
    copy:
      src: "{{ github_folder }}"/deploy_content.j2
      dest: /var/www/html/team1/index.html
   notify: restart apache

  handlers:
    - name: restart apache (httpd)
      service:
        name: httpd
        state: restarted
  - name: Deploying http.config template across our webservers
    template:
      src: "{{ github_folder }}/ansible-templates/httpd_conf.j2"
      dest: /etc/httpd/conf/httpd.conf
